### ISSUE TITLE
New User Screen

### ISSUE THREAD

**Issue by praveshkhatana** [Meshbits/pirate-wallet-layouts#19]
### Actual Design
https://www.figma.com/proto/kUcm7qs8KrR0yTbIHhBUWA/PW?page-id=0%3A1&node-id=180%3A6288&viewport=327%2C48%2C1&scaling=scale-down&starting-point-node-id=180%3A6284

<img width="366" alt="Screen Shot 2021-10-01 at 8 12 47 AM" src="https://user-images.githubusercontent.com/26607301/135557424-c115f829-546e-4917-9329-4d583e46643d.png">

### Current Design
![IMG_8602](https://user-images.githubusercontent.com/26607301/135557082-7387eb48-e326-4716-b1aa-2c1712f987c2.PNG)

### Items need to fix
- Logo Size
- 'Restore from' text and BG to separate the Restore section. Easy for us to just add the iCloud button in the future.

**Comment by lastw0nd3r** [comment]
![WhatsApp Image 2021-10-07 at 21 32 39](https://user-images.githubusercontent.com/10597606/136427475-4a8a4fae-671a-4a51-8609-0473c3430517.jpeg)

Here is how it looks now.
Thanks

**Comment by praveshkhatana** [comment]
@lastw0nd3r it's not exactly the same as what we have in Figma design.

-Please keep the same BG and Line style
-Increase font size a little bit more (on splash screen also)

<img width="362" alt="Screen Shot 2021-10-12 at 2 32 12 PM" src="https://user-images.githubusercontent.com/26607301/136926080-d338209f-4c0d-4309-ba10-b0b854a65cfd.png">

**Comment by lastw0nd3r** [comment]
@praveshkhatana I hope you meant the font size of Text "Recovery Phrase"/"Create New Wallet" ?

**Comment by lastw0nd3r** [comment]
![IMG_9167](https://user-images.githubusercontent.com/10597606/136958459-139211a1-ecaa-408b-a33d-44ea2cd946d7.PNG)

@praveshkhatana I am using the same RGB here for background of recovery phrase. Here is how it looks now.

**Comment by praveshkhatana** [comment]
I feel properties aren't matching. I hope the following code might help. 

Also, Line(2px) contains inner shadow which is creating an illusion of 2lines (one light on top and second dark at the bottom)


```
// bg


var view = UILabel()

view.frame = CGRect(x: 0, y: 0, width: 320, height: 210)

view.backgroundColor = .white


view.alpha = 0.1

var shadows = UIView()

shadows.frame = view.frame

shadows.clipsToBounds = false

view.addSubview(shadows)


let shadowPath0 = UIBezierPath(roundedRect: shadows.bounds, cornerRadius: 16)

let layer0 = CALayer()

layer0.shadowPath = shadowPath0.cgPath

layer0.shadowColor = UIColor(red: 0.051, green: 0.055, blue: 0.063, alpha: 0.85).cgColor

layer0.shadowOpacity = 1

layer0.shadowRadius = 50

layer0.shadowOffset = CGSize(width: 12, height: 24)

layer0.bounds = shadows.bounds

layer0.position = shadows.center

shadows.layer.addSublayer(layer0)


var shapes = UIView()

shapes.frame = view.frame

shapes.clipsToBounds = true

view.addSubview(shapes)


let layer1 = CAGradientLayer()

layer1.colors = [

  UIColor(red: 0.122, green: 0.129, blue: 0.145, alpha: 1).cgColor,

  UIColor(red: 0.227, green: 0.243, blue: 0.263, alpha: 1).cgColor

]

layer1.locations = [0, 1]

layer1.startPoint = CGPoint(x: 0.25, y: 0.5)

layer1.endPoint = CGPoint(x: 0.75, y: 0.5)

layer1.transform = CATransform3DMakeAffineTransform(CGAffineTransform(a: -0.99, b: 0, c: 0, d: -2.64, tx: 0.99, ty: 1.47))

layer1.bounds = shapes.bounds.insetBy(dx: -0.5*shapes.bounds.size.width, dy: -0.5*shapes.bounds.size.height)

layer1.position = shapes.center

shapes.layer.addSublayer(layer1)


shapes.layer.cornerRadius = 16


var parent = self.view!

parent.addSubview(view)

view.translatesAutoresizingMaskIntoConstraints = false

view.widthAnchor.constraint(equalToConstant: 320).isActive = true

view.heightAnchor.constraint(equalToConstant: 210).isActive = true

view.leadingAnchor.constraint(equalTo: parent.leadingAnchor, constant: 28).isActive = true

view.topAnchor.constraint(equalTo: parent.topAnchor, constant: 443).isActive = true

```

**Comment by lastw0nd3r** [comment]
Brother, we are using SwiftUI in this codebase that doesn't use UIKit (UILabel, UIView etc). 

ah ok @ 2line illusion. - That's definitely possible.

**Comment by praveshkhatana** [comment]
> Brother, we are using SwiftUI in this codebase that doesn't use UIKit (UILabel, UIView etc).
> 
> ah ok @ 2line illusion. - That's definitely possible.

I have copied it from FIGMA only, so it will help you to see & easy to differentiate all the properties with colors. You also have Figma file access. you can check all the properties of the BG layer there.

**Comment by lastw0nd3r** [comment]
yeah, I know you have shared it from figma. The stuff with SwiftUI is entirely different from what is being followed by figma/zeplin etc - they follow UIKit. Let me see how close I can get it to, though i have used the same background colors/stuff applied in there.

**Comment by praveshkhatana** [comment]
> yeah, I know you have shared it from figma. The stuff with SwiftUI is entirely different from what is being followed by figma/zeplin etc - they follow UIKit. Let me see how close I can get it to, though i have used the same background colors/stuff applied in there.

Ignore the BG part for now & just fix the line color and style

**Comment by lastw0nd3r** [comment]
How about font - "-Increase font size a little bit more (on splash screen also)?" I hope you meant the font size of Text "Recovery Phrase"/"Create New Wallet" ?

**Comment by praveshkhatana** [comment]
> How about font - "-Increase font size a little bit more (on splash screen also)?" I hope you meant the font size of Text "Recovery Phrase"/"Create New Wallet" ?

My bad sorry, I meant Logo Size
