### ISSUE TITLE
Intro Screen

### ISSUE THREAD

**Issue by praveshkhatana** [Meshbits/pirate-wallet-layouts#20]
<img width="421" alt="Screen Shot 2021-10-01 at 8 21 59 AM" src="https://user-images.githubusercontent.com/26607301/135558287-c41453e7-b446-4400-bdd9-25c91194cf1f.png">

Items that need to fix:
- Title Font color isn't '**` E9E9E9`**'. Avoid using Pure white 'FFFFFF'
- Top Nav Button
- Title Font size
- Reduce margin in-between Title & sub title
- Animation isn't smooth & it must be without any jerks or delay (in a loop)

**Comment by lastw0nd3r** [comment]
Fixed all of these. Thanks

**Comment by praveshkhatana** [comment]
- Back icon isn't correct
- Shadow missing (under coins)
- Space / Margin is too tight in between Title and Sub title


![IMG_99FF2A9009C4-1](https://user-images.githubusercontent.com/26607301/136927450-0ee92a77-61a9-4681-8bf9-e86f4cc0fb8b.jpeg)

**Comment by praveshkhatana** [comment]
And more thing,

These two are the same screen. We just need to change the Title (With slide-in-out effect) & button text when the user clicks on the intro1 screen button. (Like intro slides)

<img width="597" alt="Screen Shot 2021-10-12 at 2 43 07 PM" src="https://user-images.githubusercontent.com/26607301/136928155-211e022d-2813-43b9-a989-3470fcb2fea4.png">

**Comment by lastw0nd3r** [comment]
These two are the same screen. We just need to change the Title (With slide-in-out effect) & button text when the user clicks on the intro1 screen button. (Like intro slides)

- Ah ok, I wasn't aware this is a slide through (top text) on Get started tap.

**Comment by lastw0nd3r** [comment]
Shadow missing (under coins) - I am using two image icons for animation, shadow is tricky in here.

**Comment by praveshkhatana** [comment]
> Shadow missing (under coins) - I am using two image icons for animation, shadow is tricky in here.

Okay, we can ignore it for now and will work on this later.

**Comment by lastw0nd3r** [comment]
Done with changes.
