### ISSUE TITLE
Generate Key Phrase Screen 

### ISSUE THREAD

**Issue by praveshkhatana** [Meshbits/pirate-wallet-layouts#31]
- Header must be top align
- Reduce text size of the content

![IMG_8693](https://user-images.githubusercontent.com/26607301/137009330-7f448564-2b0c-4759-8c2b-740b3f40adc6.PNG)

**Comment by praveshkhatana** [comment]
- [x] Not showing 1 & 2nd step (steps to produce, go to 3rd screen and then click back button and start it again)



https://user-images.githubusercontent.com/26607301/137023782-5cb6e336-4cbb-4644-8700-e663a60f7fa9.MP4

**Comment by lastw0nd3r** [comment]
Fixed:

Header must be top align
Reduce text size of the content

![Simulator Screen Shot - iPhone Xs Max - 2021-10-16 at 20 06 42](https://user-images.githubusercontent.com/10597606/137591547-75ac07e8-6089-4eef-a505-5fadcb19e41b.png)

Here is how it looks @praveshkhatana 

Should I move "Step 1" to next line, it will look aligned?

Here is another snapshot with it.
![Simulator Screen Shot - iPhone Xs Max - 2021-10-16 at 20 11 29](https://user-images.githubusercontent.com/10597606/137591696-d20cdcf3-82cf-4ed8-86ed-6651108b195e.png)

**Comment by praveshkhatana** [comment]
In a single line, the same way we have in design.

**Comment by lastw0nd3r** [comment]
ah okay - cool

**Comment by lastw0nd3r** [comment]
Fixed the logical issue as well.
